### ISSUE TITLE
无法安装依赖

### ISSUE THREAD

**Issue by w311ang** [KeJunMao/jekyll-theme-mdui#47]
**I certify that I have first consulted** (check all with "x")

- [x] [Jekyll documentation ](https://jekyllrb.com/)
- [x] [jekyll-theme-mdui documentation ](http://mdui.kejun.me/#/)
- [x] [jekyll-theme-mdui issues ](https://github.com/KeJunMao/jekyll-theme-mdui/issues)

----

**I'm submitting a**  (check one with "x")

- [ ] bug report
- [ ] feature request
- [x] support request
```bash
root@localhost:~/jekyll-theme-mdui# bundler install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, andinstalling your bundle as root will break this application for all
non-root users on this machine.
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Fetching public_suffix 4.0.3
Installing public_suffix 4.0.3
Fetching addressable 2.7.0
Installing addressable 2.7.0
Using bundler 2.1.4
Fetching colorator 1.1.0
Installing colorator 1.1.0
Fetching concurrent-ruby 1.1.6
Installing concurrent-ruby 1.1.6
Fetching eventmachine 1.2.7
Installing eventmachine 1.2.7 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.5.0/gems/eventmachine-1.2.7/ext
/usr/bin/ruby2.5 -r ./siteconf20200220-19296-731zrq.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h
extconf failed, exit code 1

Gem files will remain installed in
/var/lib/gems/2.5.0/gems/eventmachine-1.2.7 for inspection.
Results logged to
/var/lib/gems/2.5.0/extensions/x86_64-linux/2.5.0/eventmachine-1.2.7/gem_make.out

An error occurred while installing eventmachine (1.2.7), and
Bundler cannot continue.
Make sure that `gem install eventmachine -v '1.2.7' --source
'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  jekyll-feed was resolved to 0.13.0, which depends on
    jekyll was resolved to 3.8.5, which depends on
      em-websocket was resolved to 0.5.1, which depends on
        eventmachine
```

**Comment by KeJunMao** [comment]
感谢，看下gemfile

**Comment by w311ang** [comment]
> 感谢，看下gemfile

仍然报错。
```bash
$ bundle install
The dependency tzinfo-data (>= 0) will be unused b
y any of the platforms Bundler is installing for. 
Bundler is installing for ruby but the dependency 
is only for x86-mingw32, x86-mswin32, x64-mingw32,
 java. To add those platforms to the bundle, run `
bundle lock --add-platform x86-mingw32 x86-mswin32
 x64-mingw32 java`.
Fetching gem metadata from https://rubygems.org/..
.........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies....
Fetching public_suffix 4.0.3
Installing public_suffix 4.0.3
Fetching addressable 2.7.0
Installing addressable 2.7.0
Using bundler 1.17.2
Fetching colorator 1.1.0
Installing colorator 1.1.0
Fetching concurrent-ruby 1.1.6
Installing concurrent-ruby 1.1.6
Fetching eventmachine 1.2.7
Installing eventmachine 1.2.7 with native extensio
ns
Gem::Ext::BuildError: ERROR: Failed to build gem
native extension.

current directory:
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.
0/gems/eventmachine-1.2.7/ext
/data/data/com.termux/files/usr/bin/ruby -I
/data/data/com.termux/files/usr/lib/ruby/2.6.0 -r
./siteconf20200223-25358-1umcp8l.rb extconf.rb
checking for -lcrypto... *** extconf.rb failed ***
Could not create Makefile due to some reason,
probably lack of necessary
libraries and/or headers.  Check the mkmf.log file
for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
--ruby=/data/data/com.termux/files/usr/bin/$(RUBY_
BASE_NAME)
        --with-ssl-dir
        --without-ssl-dir
        --with-ssl-include
        --without-ssl-include=${ssl-dir}/include
        --with-ssl-lib
        --without-ssl-lib=${ssl-dir}/lib
        --with-openssl-config
        --without-openssl-config
        --with-pkg-config
        --without-pkg-config
        --with-cryptolib
        --without-cryptolib
/data/data/com.termux/files/usr/lib/ruby/2.6.0/mkm
f.rb:467:in
`try_do': The compiler failed to generate an
executable file. (RuntimeError)
You have to install development tools first.
from
/data/data/com.termux/files/usr/lib/ruby/2.6.0/mkm
f.rb:552:in
`try_link0'
from
/data/data/com.termux/files/usr/lib/ruby/2.6.0/mkm
f.rb:570:in
`try_link'
from
/data/data/com.termux/files/usr/lib/ruby/2.6.0/mkm
f.rb:789:in
`try_func'
from
/data/data/com.termux/files/usr/lib/ruby/2.6.0/mkm
f.rb:1016:in
`block in have_library'
from
/data/data/com.termux/files/usr/lib/ruby/2.6.0/mkm
f.rb:959:in
`block in checking_for'
from
/data/data/com.termux/files/usr/lib/ruby/2.6.0/mkm
f.rb:361:in
`block (2 levels) in postpone'
from
/data/data/com.termux/files/usr/lib/ruby/2.6.0/mkm
f.rb:331:in
`open'
from
/data/data/com.termux/files/usr/lib/ruby/2.6.0/mkm
f.rb:361:in
`block in postpone'
from
/data/data/com.termux/files/usr/lib/ruby/2.6.0/mkm
f.rb:331:in
`open'
from
/data/data/com.termux/files/usr/lib/ruby/2.6.0/mkm
f.rb:357:in
`postpone'
from
/data/data/com.termux/files/usr/lib/ruby/2.6.0/mkm
f.rb:958:in
`checking_for'
from
/data/data/com.termux/files/usr/lib/ruby/2.6.0/mkm
f.rb:1011:in
`have_library'
        from extconf.rb:8:in `block in check_libs'
        from extconf.rb:8:in `all?'
        from extconf.rb:8:in `check_libs'
        from extconf.rb:95:in `<main>'

To see why this extension failed to compile,
please check the mkmf.log which can be found here:

/data/data/com.termux/files/usr/lib/ruby/gems/2.6.
0/extensions/arm-linux/2.6.0/eventmachine-1.2.7/mk
mf.log

extconf failed, exit code 1

Gem files will remain installed in
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.
0/gems/eventmachine-1.2.7
for inspection.
Results logged to
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.
0/extensions/arm-linux/2.6.0/eventmachine-1.2.7/ge
m_make.out

An error occurred while installing
eventmachine (1.2.7), and Bundler cannot continue.
Make sure that `gem install eventmachine -v
'1.2.7' --source 'https://rubygems.org/'` succeeds
before bundling.

In Gemfile:
jekyll-feed was resolved to 0.13.0, which
depends on
    jekyll was resolved to 3.8.5, which depends on
em-websocket was resolved to 0.5.1, which
depends on
        eventmachine
```

**Comment by KeJunMao** [comment]
重新clone build 分支 试试

**Comment by w311ang** [comment]
> 重新clone build 分支 试试

```bash
$ bundle install
The dependency tzinfo-data (>= 0) will be unused b
y any of the platforms Bundler is installing for. 
Bundler is installing for ruby but the dependency 
is only for x86-mingw32, x86-mswin32, x64-mingw32,
 java. To add those platforms to the bundle, run `
bundle lock --add-platform x86-mingw32 x86-mswin32
 x64-mingw32 java`.
Fetching gem metadata from https://rubygems.org/..
.........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies....
Using public_suffix 4.0.3
Using addressable 2.7.0
Using bundler 1.17.2
Using colorator 1.1.0
Using concurrent-ruby 1.1.6
Fetching eventmachine 1.2.7
Installing eventmachine 1.2.7 with native extensio
ns
Gem::Ext::BuildError: ERROR: Failed to build gem
native extension.

current directory:
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.
0/gems/eventmachine-1.2.7/ext
/data/data/com.termux/files/usr/bin/ruby -I
/data/data/com.termux/files/usr/lib/ruby/2.6.0 -r
./siteconf20200223-18755-1y994l6.rb extconf.rb
checking for -lcrypto... *** extconf.rb failed ***
Could not create Makefile due to some reason,
probably lack of necessary
libraries and/or headers.  Check the mkmf.log file
for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
--ruby=/data/data/com.termux/files/usr/bin/$(RUBY_
BASE_NAME)
        --with-ssl-dir
        --without-ssl-dir
        --with-ssl-include
        --without-ssl-include=${ssl-dir}/include
        --with-ssl-lib
        --without-ssl-lib=${ssl-dir}/lib
        --with-openssl-config
        --without-openssl-config
        --with-pkg-config
        --without-pkg-config
        --with-cryptolib
        --without-cryptolib
/data/data/com.termux/files/usr/lib/ruby/2.6.0/mkm
f.rb:467:in
`try_do': The compiler failed to generate an
executable file. (RuntimeError)
You have to install development tools first.
from
/data/data/com.termux/files/usr/lib/ruby/2.6.0/mkm
f.rb:552:in
`try_link0'
from
/data/data/com.termux/files/usr/lib/ruby/2.6.0/mkm
f.rb:570:in
`try_link'
from
/data/data/com.termux/files/usr/lib/ruby/2.6.0/mkm
f.rb:789:in
`try_func'
from
/data/data/com.termux/files/usr/lib/ruby/2.6.0/mkm
f.rb:1016:in
`block in have_library'
from
/data/data/com.termux/files/usr/lib/ruby/2.6.0/mkm
f.rb:959:in
`block in checking_for'
from
/data/data/com.termux/files/usr/lib/ruby/2.6.0/mkm
f.rb:361:in
`block (2 levels) in postpone'
from
/data/data/com.termux/files/usr/lib/ruby/2.6.0/mkm
f.rb:331:in
`open'
from
/data/data/com.termux/files/usr/lib/ruby/2.6.0/mkm
f.rb:361:in
`block in postpone'
from
/data/data/com.termux/files/usr/lib/ruby/2.6.0/mkm
f.rb:331:in
`open'
from
/data/data/com.termux/files/usr/lib/ruby/2.6.0/mkm
f.rb:357:in
`postpone'
from
/data/data/com.termux/files/usr/lib/ruby/2.6.0/mkm
f.rb:958:in
`checking_for'
from
/data/data/com.termux/files/usr/lib/ruby/2.6.0/mkm
f.rb:1011:in
`have_library'
        from extconf.rb:8:in `block in check_libs'
        from extconf.rb:8:in `all?'
        from extconf.rb:8:in `check_libs'
        from extconf.rb:95:in `<main>'

To see why this extension failed to compile,
please check the mkmf.log which can be found here:

/data/data/com.termux/files/usr/lib/ruby/gems/2.6.
0/extensions/arm-linux/2.6.0/eventmachine-1.2.7/mk
mf.log

extconf failed, exit code 1

Gem files will remain installed in
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.
0/gems/eventmachine-1.2.7
for inspection.
Results logged to
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.
0/extensions/arm-linux/2.6.0/eventmachine-1.2.7/ge
m_make.out

An error occurred while installing
eventmachine (1.2.7), and Bundler cannot continue.
Make sure that `gem install eventmachine -v
'1.2.7' --source 'https://rubygems.org/'` succeeds
before bundling.

In Gemfile:
jekyll-feed was resolved to 0.13.0, which
depends on
    jekyll was resolved to 4.0.0, which depends on
em-websocket was resolved to 0.5.1, which
depends on
        eventmachine
```

**Comment by w311ang** [comment]
> 重新clone build 分支 试试

我还拿去VPS运行了，是这个结果。
```bash
root@localhost:~/jekyll-theme-mdui# bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, andinstalling your bundle as root will break this application for all
non-root users on this machine.
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using public_suffix 4.0.3
Using addressable 2.7.0
Using bundler 2.1.4
Using colorator 1.1.0
Using concurrent-ruby 1.1.6
Fetching eventmachine 1.2.7
Installing eventmachine 1.2.7 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.5.0/gems/eventmachine-1.2.7/ext
/usr/bin/ruby2.5 -r ./siteconf20200222-25735-13wfgzm.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h
extconf failed, exit code 1

Gem files will remain installed in
/var/lib/gems/2.5.0/gems/eventmachine-1.2.7 for inspection.
Results logged to
/var/lib/gems/2.5.0/extensions/x86_64-linux/2.5.0/eventmachine-1.2.7/gem_make.out

An error occurred while installing eventmachine (1.2.7), and
Bundler cannot continue.
Make sure that `gem install eventmachine -v '1.2.7' --source
'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  jekyll-feed was resolved to 0.13.0, which depends on
    jekyll was resolved to 4.0.0, which depends on
      em-websocket was resolved to 0.5.1, which depends on
        eventmachine
```

**Comment by KeJunMao** [comment]
这边是可以的哎

**Comment by w311ang** [comment]
> 这边是可以的哎

问题找到了，原来是我没装`ruby-dev`，通过[这里](https://stackoverflow.com/questions/20559255/error-while-installing-json-gem-mkmf-rb-cant-find-header-files-for-ruby)方法运行一条`apt install ruby-dev`就解决了。

**Comment by w311ang** [comment]
那这样的话Termux就不支持了。
```bash
$ apt install ruby-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package ruby-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  ruby

E: Package 'ruby-dev' has no installation candidate
```

**Comment by w311ang** [comment]
有意思咯。https://wiki.termux.com/wiki/No_more_-dev_packages

**Comment by w311ang** [comment]
VPS成功。
```bash
root@localhost:~/jekyll-theme-mdui# bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, andinstalling your bundle as root will break this application for all
non-root users on this machine.
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using public_suffix 4.0.3
Using addressable 2.7.0
Using bundler 2.1.4
Using colorator 1.1.0
Using concurrent-ruby 1.1.6
Using eventmachine 1.2.7
Using http_parser.rb 0.6.0
Using em-websocket 0.5.1
Using ffi 1.12.2
Using forwardable-extended 2.6.0
Using i18n 1.8.2
Fetching sassc 2.2.1
Installing sassc 2.2.1 with native extensions
Fetching jekyll-sass-converter 2.1.0
Installing jekyll-sass-converter 2.1.0
Fetching rb-fsevent 0.10.3
Installing rb-fsevent 0.10.3
Fetching rb-inotify 0.10.1
Installing rb-inotify 0.10.1
Fetching listen 3.2.1
Installing listen 3.2.1
Fetching jekyll-watch 2.2.1
Installing jekyll-watch 2.2.1
Fetching kramdown 2.1.0
Installing kramdown 2.1.0
Fetching kramdown-parser-gfm 1.1.0
Installing kramdown-parser-gfm 1.1.0
Fetching liquid 4.0.3
Installing liquid 4.0.3
Fetching mercenary 0.3.6
Installing mercenary 0.3.6
Fetching pathutil 0.16.2
Installing pathutil 0.16.2
Fetching rouge 3.16.0
Installing rouge 3.16.0
Fetching safe_yaml 1.0.5
Installing safe_yaml 1.0.5
Fetching unicode-display_width 1.6.1
Installing unicode-display_width 1.6.1
Fetching terminal-table 1.8.0
Installing terminal-table 1.8.0
Fetching jekyll 4.0.0
Installing jekyll 4.0.0
Fetching jekyll-feed 0.13.0
Installing jekyll-feed 0.13.0
Fetching jekyll-paginate 1.1.0
Installing jekyll-paginate 1.1.0
Fetching jekyll-sitemap 1.4.0
Installing jekyll-sitemap 1.4.0
Fetching jekyll-theme-mdui 0.5.4
Installing jekyll-theme-mdui 0.5.4
Bundle complete! 6 Gemfile dependencies, 31 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Post-install message from jekyll:
-------------------------------------------------------------------------------------
Jekyll 4.0 comes with some major changes, notably:

  * Our `link` tag now comes with the `relative_url` filter incorporated into it.
    You should no longer prepend `{{ site.baseurl }}` to `{% link foo.md %}`
    For further details: https://github.com/jekyll/jekyll/pull/6727

  * Our `post_url` tag now comes with the `relative_url` filter incorporated into it.
    You shouldn't prepend `{{ site.baseurl }}` to `{% post_url 2019-03-27-hello %}`
    For further details: https://github.com/jekyll/jekyll/pull/7589

  * Support for deprecated configuration options has been removed. We will no longer
    output a warning and gracefully assign their values to the newer counterparts
    internally.
-------------------------------------------------------------------------------------
```

**Comment by w311ang** [comment]
我按照[这个](https://stackoverflow.com/questions/19697359/ruby-debug-could-not-create-makefile-due-to-some-reason-probably-lack-of-necess)的要求找到了`mkmf.log`文件，内容如下：
```
"arm-linux-androideabi-clang -o conftest -I/data/data/com.termux/files/usr/include/ruby-2.6.0/arm-linux-androideabi -I/data/data/com.termux/files/usr/include/ruby-2.6.0/ruby/backward -I/data/data/com.termux/files/usr/include/ruby-2.6.0 -I. -I/data/data/com.termux/files/usr/include    -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -Oz -fstack-protector-strong -fPIC conftest.c  -L. -L/data/data/com.termux/files/usr/lib -L. -L/data/data/com.termux/files/usr/lib -march=armv7-a -Wl,-z,relro,-z,now -landroid-support -fstack-protector-strong -rdynamic -Wl,-export-dynamic     -lruby  -lm   -lc" checked program was:
/* begin */
1: #include "ruby.h"
2:                                                3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }                                              /* end */

package configuration for openssl is not found
```

**Comment by w311ang** [comment]
Termux安装`eventmachine`出错的问题已解决，参阅了[这个Question](https://stackoverflow.com/questions/19697359/ruby-debug-could-not-create-makefile-due-to-some-reason-probably-lack-of-necess)和[这个Issue](https://github.com/Smashing/smashing/issues/28)后得出。
只要在执行`bundle install`前执行以下命令就不会出错了。
```bash
apt install build-essential
```
但是`sassc`编译出错尚未解决。

**Comment by w311ang** [comment]
不过还是推荐在VPS上安装依赖，手机上还是太慢了。

**Comment by w311ang** [comment]
Termux编译`sassc`出错。
```bash
$ bundle install
The dependency tzinfo-data (>= 0) will be unused b
y any of the platforms Bundler is installing for. 
Bundler is installing for ruby but the dependency 
is only for x86-mingw32, x86-mswin32, x64-mingw32,
 java. To add those platforms to the bundle, run `
bundle lock --add-platform x86-mingw32 x86-mswin32
 x64-mingw32 java`.
Fetching gem metadata from https://rubygems.org/..
.........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies....
Fetching public_suffix 4.0.3
Installing public_suffix 4.0.3
Fetching addressable 2.7.0
Installing addressable 2.7.0
Using bundler 1.17.2
Fetching colorator 1.1.0
Installing colorator 1.1.0
Fetching concurrent-ruby 1.1.6
Installing concurrent-ruby 1.1.6
Fetching eventmachine 1.2.7
Installing eventmachine 1.2.7 with native extensio
ns
Fetching http_parser.rb 0.6.0
Installing http_parser.rb 0.6.0 with native extens
ions
Fetching em-websocket 0.5.1
Installing em-websocket 0.5.1
Fetching ffi 1.12.2
Installing ffi 1.12.2 with native extensions
Fetching forwardable-extended 2.6.0
Installing forwardable-extended 2.6.0
Fetching i18n 1.8.2
Installing i18n 1.8.2
Fetching sassc 2.2.1
Installing sassc 2.2.1 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem
native extension.

current directory:
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.
0/gems/sassc-2.2.1/ext
/data/data/com.termux/files/usr/bin/ruby -I
/data/data/com.termux/files/usr/lib/ruby/2.6.0 -r
./siteconf20200223-29272-142ysqr.rb extconf.rb
creating Makefile

current directory:
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.
0/gems/sassc-2.2.1/ext
make "DESTDIR=" clean

current directory:
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.
0/gems/sassc-2.2.1/ext
make "DESTDIR="
compiling ./libsass/src/ast.cpp
compiling ./libsass/src/ast2c.cpp
compiling ./libsass/src/ast_fwd_decl.cpp
compiling ./libsass/src/ast_sel_cmp.cpp
compiling ./libsass/src/ast_sel_unify.cpp
compiling ./libsass/src/ast_selectors.cpp
compiling ./libsass/src/ast_supports.cpp
compiling ./libsass/src/ast_values.cpp
compiling ./libsass/src/backtrace.cpp
compiling ./libsass/src/base64vlq.cpp
compiling ./libsass/src/bind.cpp
compiling ./libsass/src/c2ast.cpp
compiling ./libsass/src/c99func.c
compiling ./libsass/src/cencode.c
compiling ./libsass/src/check_nesting.cpp
compiling ./libsass/src/color_maps.cpp
compiling ./libsass/src/constants.cpp
compiling ./libsass/src/context.cpp
compiling ./libsass/src/cssize.cpp
compiling ./libsass/src/emitter.cpp
compiling ./libsass/src/environment.cpp
compiling ./libsass/src/error_handling.cpp
compiling ./libsass/src/eval.cpp
compiling ./libsass/src/expand.cpp
compiling ./libsass/src/extend.cpp
compiling ./libsass/src/file.cpp
compiling ./libsass/src/fn_colors.cpp
compiling ./libsass/src/fn_lists.cpp
compiling ./libsass/src/fn_maps.cpp
compiling ./libsass/src/fn_miscs.cpp
compiling ./libsass/src/fn_numbers.cpp
compiling ./libsass/src/fn_selectors.cpp
compiling ./libsass/src/fn_strings.cpp
compiling ./libsass/src/fn_utils.cpp
compiling ./libsass/src/inspect.cpp
compiling ./libsass/src/json.cpp
compiling ./libsass/src/lexer.cpp
compiling ./libsass/src/listize.cpp
compiling ./libsass/src/memory/SharedPtr.cpp
compiling ./libsass/src/node.cpp
compiling ./libsass/src/operators.cpp
compiling ./libsass/src/output.cpp
compiling ./libsass/src/parser.cpp
compiling ./libsass/src/plugins.cpp
compiling ./libsass/src/position.cpp
compiling ./libsass/src/prelexer.cpp
compiling ./libsass/src/remove_placeholders.cpp
compiling ./libsass/src/sass.cpp
compiling ./libsass/src/sass2scss.cpp
compiling ./libsass/src/sass_context.cpp
compiling ./libsass/src/sass_functions.cpp
compiling ./libsass/src/sass_util.cpp
compiling ./libsass/src/sass_values.cpp
compiling ./libsass/src/source_map.cpp
compiling ./libsass/src/subset_map.cpp
compiling ./libsass/src/to_value.cpp
compiling ./libsass/src/units.cpp
compiling ./libsass/src/utf8_string.cpp
compiling ./libsass/src/util.cpp
compiling ./libsass/src/util_string.cpp
compiling ./libsass/src/values.cpp
linking shared-object sassc/libsass.so
clang-9: error: unable to execute command:
Segmentation fault
clang-9: error: linker command failed due to
signal (use -v to see invocation)
make: *** [Makefile:262: libsass.so] Error 254

make failed, exit code 2

Gem files will remain installed in
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.
0/gems/sassc-2.2.1
for inspection.
Results logged to
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.
0/extensions/arm-linux/2.6.0/sassc-2.2.1/gem_make.
out

An error occurred while installing sassc
(2.2.1), and Bundler cannot continue.
Make sure that `gem install sassc -v '2.2.1'
--source 'https://rubygems.org/'` succeeds before
bundling.

In Gemfile:
jekyll-feed was resolved to 0.13.0, which
depends on
    jekyll was resolved to 4.0.0, which depends on
jekyll-sass-converter was resolved to 2.1.0,
which depends on
        sassc
```

**Comment by w311ang** [comment]
放弃Termux了，编译问题还是挺难整的。

**Comment by w311ang** [comment]
这篇文章可能会对修复这个问题有所帮助。https://blog.akehir.com/2017/05/building-node-sass-libsass-python.html

**Comment by w311ang** [comment]
> Termux安装`eventmachine`出错的问题已解决，参阅了[这个Question](https://stackoverflow.com/questions/19697359/ruby-debug-could-not-create-makefile-due-to-some-reason-probably-lack-of-necess)和[这个Issue](https://github.com/Smashing/smashing/issues/28)后得出。
> 只要在执行`bundle install`前执行以下命令就不会出错了。
> 
> ```shell
> apt install build-essential
> ```
> 
> 但是`sassc`编译出错尚未解决。

VPS上不成功也可以用。
